#!/bin/sh

set -e
set -x

if [ "$1" = "" ]; then
  submodule="https://github.com/krlmlr/makeR.git"
elif [ -d "$1" -a -d "$1/.git" -a -f "$1/Makefile" ]; then
  submodule="$1"
else
  submodule="git@github.com:$1/makeR.git"
fi

rm -rf .git/modules/makeR
git submodule add "$submodule" makeR

echo "-include makeR/Makefile

init:
	git submodule update --init" > Makefile
echo /Makefile >> .Rbuildignore
echo /makeR >> .Rbuildignore
git add Makefile .Rbuildignore
git commit -m "install makeR"

