#!/bin/sh

set -e

rm -f Makefile
cp makeR/Makefile.tmpl Makefile

Rscript -e 'devtools::use_build_ignore(c("Makefile", "Makefile.in", "makeR"))'
git add Makefile .Rbuildignore
if ! $(basename $0)/git_is_clean; then git commit -m "install makeR as subtree"; fi
